config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'login#index', as: :login
  post 'login' => 'login#authenticate', as: :authenticate
  get 'logout' => 'login#logout', as: :logout
  get '/' => 'home#index', as: :home
  root 'home#index'

  resources :registrations
  resources :professors
  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def authenticate
    @student = Student.find_by(netid: params[:netid], password: params[:password])
    if @student
      flash[:message] = "Welcome #{@student.f_name}"

      session[:student_id] = @student.id
      session[:admin] = @student.admin
      redirect_to home_path

    else
      flash[:message] = "You have not been logged in. Student can't be found"
      redirect_to login_path
    end

  end

  def logout
    session[:student_id] = nil
    flash[:message] = "You have been logged out"
    redirect_to login_path
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/authenticate.html.erb
<h1>Login#authenticate</h1>
<p>Find me in app/views/login/authenticate.html.erb</p>

app/views/login/index.html.erb
<h1>Login</h1>

<%= form_tag authenticate_path do %>
  <p>
    <%= label_tag :netid %>
    <%= text_field_tag :netid %>
  </p>

  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= submit_tag :login %>
  </p>
<% end %>

app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>