config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'login#index', as: :login
  post 'login' => 'login#authenticate', as: :authenticate
  get 'logout' => 'login#logout', as: :logout
  get '/' => 'home#index', as: :home
  root 'home#index'

  resources :registrations
  resources :professors
  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <h2>Helpful Links</h2>
  <p>
    <ul>
      <li> <%= link_to "Home", "/" %> </li>

        <% if session[:admin] %>
          <li><%= link_to "Registrations", registrations_path %></li>
          <li><%= link_to "Logout", logout_path %></li>
          <li><%= "Admin only Links" %></li>
          <li><%= link_to "Professors", professors_path %></li>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Students", students_path %></li>

        <% elsif session[:student_id] %>
            <li><%= link_to "Registrations", registrations_path %></li>
            <li><%= link_to "Logout", logout_path %></li>

        <% else %>
            <li><%= link_to "Login", login_path %></li>
        <% end %>


    </ul>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div class="all">
  <body>
    <header>
      <h1>Schedule Tracker</h1>
    </header>

    <%= render "layouts/sidebar" %>

    <div class="main">
      <%= yield %>
    </div>

    <div class="primary">
      <% if flash[:message] %>
        <p class="flash-message">
        <%= flash[:message] %></p>
      <% end %>

      </div>

    <footer>
      <p>
        Welcome to the schedule tracker app!
      </p>
    </footer>
  </body>
</div>
</html>